getImagesFromTwitter/urls.py
from django.urls import path
from getImagesFromTwitter import views


app_name = 'getImagesFromTwitter'
urlpatterns = [
        path('', views.index, name='index'),
        path('get_token/', views.get_token, name='get_token'),
        path('login_twitter/', views.login_twitter, name='login_twitter'),
        path('get_images/', views.get_images_from_name, name='get_images'),
        path('label_to_images/', views.label_to_images, name='label'),
        path('display_labeled_images/', views.display_labeled_images, name='labeled'),
]

imageclf/urls.py
from django.urls import path
from imageclf import views


app_name = 'imageclf'
urlpatterns = [
        path('', views.index, name='index'),
        path('clf', views.get_and_classify_images, name='clf'),
]

twitterImages/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/imageclf/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('getImagesFromTwitter/', include('getImagesFromTwitter.urls')),
    path('imageclf/', include('imageclf.urls')),
]

getImagesFromTwitter/models.py
from django.db import models
from django.contrib.auth.models import User


class Image(models.Model):
    created_at = models.DateTimeField(null=True)
    id_str = models.CharField(max_length=50)
    screen_name = models.CharField(max_length=100)
    media_id_str = models.CharField(max_length=50)
    media_url_https = models.URLField()
    text = models.BinaryField(blank=True)
    hashtags_text = models.TextField( blank=True)
    retweet_count = models.IntegerField()
    favorite_count = models.IntegerField()
    has_multiple_media = models.BooleanField()
    label = models.IntegerField(null=True)
    labeler = models.ForeignKey(
            User,
            on_delete=models.SET_NULL,
            null=True,
    )
    subdata1 = models.TextField(null=True)
    subdata2 = models.TextField(null=True)
    subdata3 = models.IntegerField(null=True)

getImagesFromTwitter/forms.py
from django import forms
from getImagesFromTwitter.models import Image


class IllustratorForm(forms.Form):
    name = forms.CharField(max_length=100)
    CHOICES = [
            ('save', 'dbに保存する'),
            ('discard', '保存しない'),
    ]
    save_status = forms.ChoiceField(
            widget=forms.RadioSelect,
            choices=CHOICES,
    )


class ImageLabelForm(forms.ModelForm):
    """modelsで直接RadioSelect widgetを選ぶことができないため書き換える
    """
    class Meta:
        model = Image
        CHOICES = [
                (0, 'イラスト'),
                (1, '写真'),
                (2, 'スクショ'),
                (3, 'そのほか'),
        ]
        fields = ('label',)
        widgets = {
                'label': forms.RadioSelect(choices=CHOICES)
        }


class DisplaySelectForm(forms.Form):
    # この場合strになってしまう
    CHOICES = [
                (0, 'イラスト'),
                (1, '写真'),
                (2, 'スクショ'),
                (3, 'そのほか'),
    ]
    label = forms.ChoiceField(
            widget=forms.RadioSelect,
            choices=CHOICES,
    )

getImagesFromTwitter/views.py
import codecs
import datetime
import json
import os
from requests_oauthlib import OAuth1Session
from urllib.parse import parse_qsl

from django import forms
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django import views
from getImagesFromTwitter.models import Image
from getImagesFromTwitter.forms import ImageLabelForm, IllustratorForm
from getImagesFromTwitter.forms import DisplaySelectForm


APIKEY = os.environ.get('ApiKey_TW')
APISECRETKEY = os.environ.get('ApiSecretKey_TW')
# 開発環境->DEBUG = True, CentOS->DEBUG = Falseで
# 区別するので、以下のように分岐させる。
# settings.pyから読むことはできない。(おそらくここで読む方が先)
DEBUG = os.environ.get('DEBUG')
if DEBUG == 'True':
    oauth_callback = "http://127.0.0.1:8000/getImagesFromTwitter/get_token/"
elif DEBUG == 'False':
    # 後で撮り直す！！
    oauth_callback = "http://qtatsu.com/getImagesFromTwitter/get_token/"
else:
    oauth_callback = "Chack DEBUG vars."


@login_required
def index(request):
    return render(
        request,
        'getImagesFromTwitter/base.html',
        {},
    )


@login_required
def login_twitter(request):
    """OAuth1認証する."""
    twitter_session = OAuth1Session(APIKEY, APISECRETKEY)
    response = twitter_session.post(
            url="https://api.twitter.com/oauth/request_token",
            params={
                'oauth_callback': oauth_callback
            },
    )
    if response.status_code == 200:
        # response.contentはbytesかつxxx=yyy&zzz=qqqという形式なので、パースしてdictへ変換.
        request_token = dict(parse_qsl(response.content.decode('utf-8')))
        auth_url = "https://api.twitter.com/oauth/authenticate"
        auth_endpoint = f"{auth_url}?oauth_token={request_token['oauth_token']}"
        return HttpResponseRedirect(auth_endpoint)
    else:
        return HttpResponse(
                "loginに失敗しました:{}:{}".format(
                    oauth_callback,
                    response.status_code,
                )
        )

@login_required
def get_token(request):
    """login_twitterでtwitter認証画面=>認証完了後, call_backする場所.

    画面としては存在せず、urlのoauth_tokenとverifierの値取得のために利用する.
    developerページに登録してあるのはこの関数へのURL.
    """
    # request.get_full_path()は冗長だったので直接クエリ取った。
    querydict = request.GET
    oauth_token = querydict.get('oauth_token')
    oauth_verifier = querydict.get('oauth_verifier')
    tweet_session = OAuth1Session(
            APIKEY, APISECRETKEY, oauth_token, oauth_verifier
    )
    response = tweet_session.post(
            'https://api.twitter.com/oauth/access_token',
            params={
                'oauth_verifier': oauth_verifier
            },
    )
    if response.status_code == 200:
        access_token = dict(parse_qsl(response.content.decode('utf-8')))
        # sessionにtokenを保存し、login状態を保つ.
        request.session['access_token'] = access_token
        return redirect(to=reverse('getImagesFromTwitter:index'))
    else:
        return HttpResponse('tokenが取得できません')

@login_required
def get_images_from_name(request):
    """twitter user名(@以下)から,可能な限り画像ツイートを回収する。

    複数画像の場合、画像ごとのobjectに分ける。
    """
    if request.method == 'POST':
        form = IllustratorForm(request.POST)
        if form.is_valid():
            # returns tweets.=>一時的にdbに保存...つーか永続保存かな。
                # media_idが被ってた場合排除した方が良さそう。
            # access_tokenはありきで、セッション確率くらいまでdef化けする？
            # かぶってからわければいい？可読性次第だな。
            twitter_session = OAuth1Session(APIKEY, APISECRETKEY)
            # 初回はmax_idを指定したくない。Noneにすれば指定なしと同じになる。
            max_id = None
            n = 3200 / 200   # ツイート取得可能数
            tweets_with_photo = []
            for i in range(int(n)):
                params = {
                        'screen_name': form.cleaned_data.get('name'),
                        'count': 200,           # 1回のgetにおける最大値
                        'exclude_replies': True,
                        'include_rts': False,
                        'max_id': max_id
                }
                response = twitter_session.get(
                        url='https://api.twitter.com/1.1/statuses/user_timeline.json',
                        params=params
                )
                if response.status_code != 200:
                    return HttpResponse('取得失敗しました')
                tweets = json.loads(response.text)
                # 3,200ツイート以下だった場合、取得できなかった時点で抜いて効率化する。
                if tweets == []:
                    break
                for tweetobj in tweets:
                    # twitterは複数種類mediaを同時に添付できないのでidx0のみ見れば良いはず.
                    try:
                        mediatype = tweetobj['extended_entities']['media'][0]['type'] 
                    except Exception:
                        mediatype = None
                    if mediatype and mediatype == 'photo':
                        # mediasはgenerator.
                        medias = get_items_from_tweet(tweetobj)
                        tweets_with_photo.append(medias)
                # 最後(oldest)のtw objectのid由来。
                max_id = tweetobj.get('id') - 1
            texts = '<p>{}個のオブジェクト</p>'.format(len(tweets_with_photo))
            if tweets_with_photo == []:
                return HttpResponse('画像はありません')

            # dbへの保存処理ブロック>>わかりにくいから関数化する？
            tweets_for_render = [] # tempaltでgeneratorが動かないからこうした。書き直したい.
            for medias in tweets_with_photo:
                for media in medias:
                    # 表示用にtextをbynary=>strにする
                    media_cp = media.copy()
                    media_cp['text'] = codecs.decode(media_cp.get('text',''))
                    tweets_for_render.append(media_cp)
                    # PILのImageと同じで紛らわしい名前だから良くない！！
                    # tweet_urlを消す。よくない処理なのでリファクタリングする。
                    media.pop('tweet_url')
                    image = Image(**media)
                    if form.cleaned_data.get('save_status') == 'save':
                        # すでにmediaが存在しないかチェック。
                        existing = Image.objects.filter(
                                media_id_str__exact=media.get('media_id_str')
                        )
                        if existing:
                            texts += '<p>{}はすでに保存されています</p>'.format(
                                    media.get('media_id_str')
                            )
                        else:
                            image.save()
            # 取得した画像の表示
            # redirectした方がいいと思うが、ユーザが使うメソではないので妥協。 
            # >>関数化して、ユーザが使う部分はそれを再利用して作り直す。
            # 画像もdbも一時保存して、それを同定するフラグをurlかsessionで渡す。
            return render(
                request,
                'getImagesFromTwitter/images_list.html', 
                {
                    'tweets': tweets_for_render,
                }

            )
    else:
        form = IllustratorForm()
    # GET時とform.is_varid() == False時はform入力画面へ。
    return render(
            request,
            'getImagesFromTwitter/get_illustrator_name.html',
            {
                'form': form,
            }
    )

@login_required
def label_to_images(request):
    """db中のデータのうち、未ラベルのデータを取得してラベルする"""
    ImageLabelFormSet = forms.modelformset_factory(
            Image,
            form=ImageLabelForm,
    )
    allimages = Image.objects.all()
    total_images_number = allimages.count()
    labeled_images_number = allimages.exclude(label__exact=None).count()
    illust_images = allimages.filter(label__exact=0).count()
    photo_images = allimages.filter(label__exact=1).count()
    sc_images = allimages.filter(label__exact=2).count()
    other_images = allimages.filter(label__exact=3).count()
    img_counts = {
            'total': total_images_number,
            'labeled': labeled_images_number,
            'illust': illust_images,
            'photo': photo_images,
            'sc': sc_images,
            'other': other_images,
    }

    if request.method == 'POST':
        # docに従ってここでquery取得したが、これGET時とPOST時の間で他から変更
        # される可能性ないのか？きちんと閉じられているのだろうか?

        # label無しの最も小さいid + 20をmax_idとし
        # 、それ以下をとることで20個取得する。
        no_label_images = Image.objects.filter(label__exact=None)
        if not no_label_images:
            return HttpResponse('未ラベルのサンプルはありません')
        max_id = no_label_images.order_by('id')[0].id + 10
        images = no_label_images.filter(id__lt=max_id)
        formset = ImageLabelFormSet(
                request.POST,
                queryset=images
        )
        if formset.is_valid():
            f = formset.save()
            for image in f:
                # なぜかこれ逆から設定しなければと思ってたけどそんなことなかった。
                image.labeler = request.user
                image.save()
            return redirect(
                    reverse('getImagesFromTwitter:label'),
            )
    else:   # GET時
        # 冗長だし異なるdata取る可能性あるように思うが
        # django公式documentではここでもquery取得してる。
        no_label_images = Image.objects.filter(label__exact=None)
        if not no_label_images:
            return HttpResponse('未ラベルのサンプルはありません')
        max_id = no_label_images.order_by('id')[0].id + 10
        images = no_label_images.filter(id__lt=max_id)
        formset = ImageLabelFormSet(queryset=images)
        # template場でb''をデコードできないのでここで変換する。
        texts = [codecs.decode(img.text) for img in images]
    # template内部でzipできないのでこちらで作った。
    # formsetも別途渡しているのは、management_form部分が必須なので。
    zips = zip(images, formset, texts)
    return render(
            request,
            'getImagesFromTwitter/labeling.html',
            {
                'formset': formset,
                'zips': zips,
                # 'total_images_number': total_images_number,
                # 'labeled_images_number': labeled_images_number,
                'img_counts': img_counts,
            }
    )


@login_required
def display_labeled_images(request):
    """ラベルづけされたイメージを表示する。"""
    if request.method == 'POST':

getImagesFromTwitter/templates/getImagesFromTwitter/access_token_dead.html
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset='utf-8'>
    <title>access_token_dead</title>
  </head>
  <body>
    <main>
      <div>
        <a href='{% url 'getImagesFromTwitter:index' %}'>
          access_tokenを撮り直してください
        </a>
      </div>
    </main>
  </body>
</html>

getImagesFromTwitter/templates/getImagesFromTwitter/base.html
<!DOCTYPE html>

{% load static %}

<html lang='ja'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-=no">
    <title>login to twitter</title>
  </head>
  <body>
    <main>
      {% comment %}request.session辞書にアクセスできたわ{% endcomment %}
      {% if request.session.access_token %}
      <p>現在access_tokenを持っています</p>
      {% endif %}
      <div> 
        <a href="{% url 'getImagesFromTwitter:login_twitter' %}">
          Twitterにloginする
        </a>
      </div>
      <div>
        <a href="{% url 'getImagesFromTwitter:get_images' %}">
          いらすとげったー
        </a>
      <div>
        <a href="{% url 'getImagesFromTwitter:label' %}">
          らべりんぎんぐ
        </a>
      </div>
      <div>
        <a href="{% url 'getImagesFromTwitter:labeled' %}">
          ぶんるいちぇっかー
        </a>
      </div>
      </div>
    </main>
  </body>
</html>

getImagesFromTwitter/templates/getImagesFromTwitter/display_labeled_images_get.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset='utf-8'>
    <title>labeled images</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href={% static "node_modules/bootstrap/dist/css/bootstrap.min.css" %}>
  </head>
  <body>
    <main>
      <a class="btn btn-primary"
         href="{% url 'getImagesFromTwitter:index' %}">
        indexに戻る
      </a>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <button class="btn btn-secondary">GO</button>
      </form>
    </main>
    <script src={% static "node_modules/jquery/dist/jquery.slim.min.js" %}></script>
    <script src={% static "node_modules/popper.js/dist/umd/popper.min.js" %}></script>
    <script src={% static "node_modules/bootstrap/dist/js/bootstrap.min.js" %}></script>
  </body>
</html>

getImagesFromTwitter/templates/getImagesFromTwitter/display_labeled_images_post.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset='utf-8'>
    <title>labeled images</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href={% static "node_modules/bootstrap/dist/css/bootstrap.min.css" %}>
    <style>
      .sizeofthumb {
        width: 20vw;
        height: auto;
      }
    </style>
  </head>
  <body>
    <main>
      <a class="btn btn-primary"
         href="{% url 'getImagesFromTwitter:index' %}">
        indexに戻る
      </a>
      <div class="d-flex flex-wrap">
          {% for img in images %}
          <div class="sizeofthumb p-2">
                  <img class="img-fluid" src="{{ img.media_url_https }}">
                  <p>{{ img.screen_name }}</p>
          </div>
          {% endfor %}
      </div>
      <p>{{label}}</P>
    </main>
    <script src={% static "node_modules/jquery/dist/jquery.slim.min.js" %}></script>
    <script src={% static "node_modules/popper.js/dist/umd/popper.min.js" %}></script>
    <script src={% static "node_modules/bootstrap/dist/js/bootstrap.min.js" %}></script>
  </body>
</html>

getImagesFromTwitter/templates/getImagesFromTwitter/get_illustrator_name.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset='utf-8'>
    <title>illustrator name</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href={% static "node_modules/bootstrap/dist/css/bootstrap.min.css" %}>
  <head>
  
  <body>
    <main>
      <form action="{% url 'getImagesFromTwitter:get_images' %}" method='POST'>
        {% csrf_token %}
        {% for fields in form %}
          <ul>
          {% for field in fields %}
            <li>
              {{ field }}
            </li>
          {% endfor %}
          </ul>
        {% endfor %}
        <button type="submit" class="btn btn-primary">GO!</button>
      </form>
    </main>
    <script src={% static "node_modules/jquery/dist/jquery.slim.min.js" %}></script>
    <script src={% static "node_modules/popper.js/dist/umd/popper.min.js" %}></script>
    <script src={% static "node_modules/bootstrap/dist/js/bootstrap.min.js" %}></script>
  </body>
</html>

getImagesFromTwitter/templates/getImagesFromTwitter/get_images.html
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset='utf-8'>
    <title>get images</title>
  </head>
  <body>
    <main>
      <form action="#"
            method="POST">
        {% csrf_token %}
        {% for field in form %}
          <ol>
          {% for sp in field %}
            <li>
            {{ sp }}
            </li>
          {% endfor %}
          </ol>
        {% endfor %}
        <button type="submit">GO!</button>
      </form>
    </main>
  </body>
</html>

getImagesFromTwitter/templates/getImagesFromTwitter/images_list.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset='utf-8'>
    <title>images</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href={% static "node_modules/bootstrap/dist/css/bootstrap.min.css" %}>
    <style>
      .sizeofthumb {
        width: 20vw;
        height: auto;
      }
    </style>
  </head>
  <body>
    <main>
      <a class="btn btn-primary"
         href="{% url 'getImagesFromTwitter:index' %}">
        indexに戻る
      </a>
      <div class="d-flex flex-wrap">
          {% comment %}
          ぼくがよくやるforloop.counter|mod:xはあんまりよくないと気がついた。
          flexboxの利点失ってる。flex-wrapで改行アリで並べて、
          中身のdivは自分でstyle指定(sizeofthumbクラス)し、画面サイズ(vw)で
          width決めてheightはautoにした(これがいいかは不明)。{% endcomment %}
          {% for media in tweets %}
          <div class="sizeofthumb p-2">
              {% for key, value in media.items %}
                  {% if key == 'media_url_https' %}
                    <img class="img-fluid" src="{{ value }}">
                  {% endif %}
                  {% if key == 'text' %}
                    <p>{{ value }}</p>
                  {% endif %}
              {% endfor %}
          </div>
          {% endfor %}
      </div>
    </main>
    <script src={% static "node_modules/jquery/dist/jquery.slim.min.js" %}></script>
    <script src={% static "node_modules/popper.js/dist/umd/popper.min.js" %}></script>
    <script src={% static "node_modules/bootstrap/dist/js/bootstrap.min.js" %}></script>
  </body>
</html>

getImagesFromTwitter/templates/getImagesFromTwitter/labeling.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset='utf-8'>
    <title>labeling</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href={% static "node_modules/bootstrap/dist/css/bootstrap.min.css" %}>
    <style>
      .sizeofthumb {
        width: 20vw;
        height: auto;
      }
    </style>
  </head>
  <body>
    <main>
      <a class="btn btn-primary"
         href="{% url 'getImagesFromTwitter:index' %}">
        indexに戻る
      </a>
      <div class="p-2 m-2">
        <p class="text-primary m-2 p-2">
          ラベル済み / トータル画像数 :
          <span class="bg-primary text-white font-weight-bold m-2 p-2">
            {{ img_counts.labeled }} / {{ img_counts.total }}
          </span>
        </p>
        <p>
          イラスト: <span class="font-weight-bold">{{ img_counts.illust }}<span> 枚
        </p>
        <p>
          写真:  <span class="font-weight-bold">{{ img_counts.photo }}<span> 枚
        </p>
        <p>
          スクショ:  <span class="font-weight-bold">{{ img_counts.sc }}<span> 枚
        </p>
        <p>
          その他:   <span class="font-weight-bold">{{ img_counts.other }}<span> 枚
        </p>
      </div>
      <form method='POST'>
        <div class="d-flex flex-wrap">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for image, form, txt in zips %}
              <div class="sizeofthumb p-2 border">
                <img class="img-fluid" src="{{ image.media_url_https }}">
                <p>{{ image.screen_name }}</p>
                <p>{{ txt }}</p>
                {{ form }} 
              </div>
            {% endfor %}
        </div>
        <button class="m-2 btn btn-danger" type='submit'>ラベル完了!!</button>
      </form>
    </main>
    <script src={% static "node_modules/jquery/dist/jquery.slim.min.js" %}></script>
    <script src={% static "node_modules/popper.js/dist/umd/popper.min.js" %}></script>
    <script src={% static "node_modules/bootstrap/dist/js/bootstrap.min.js" %}></script>
  </body>
</html>