imageclf/urls.py
from django.urls import path
from imageclf import views


app_name = 'imageclf'
urlpatterns = [
        path('', views.index, name='index'),
        path('clf', views.get_and_classify_images, name='clf'),
]

twitterImages/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/imageclf/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('getImagesFromTwitter/', include('getImagesFromTwitter.urls')),
    path('imageclf/', include('imageclf.urls')),
]

imageclf/models.py
from django.db import models

# Create your models here.

imageclf/forms.py
from django import forms


class IllustratorForm(forms.Form):
    name = forms.CharField(
            max_length=100,
            label="ユーザID:",
            initial='qtatsu_q'
    )
    CHOICES = [
            ('clf', 'イラスト/写真を分類する'),
            ('noclf', '分類しない'),
    ]
    clf_status = forms.ChoiceField(
            widget=forms.RadioSelect,
            choices = CHOICES,
            label=""
    )
    img_number = forms.IntegerField(
            initial=50,
            label='取得枚数:',
            help_text='取得枚数が多すぎる場合、取得と分類に1,2分かかることがあります。\
                      <br>また画像以外のツイートが非常に多いユーザの場合、\
                      ツイート取得に時間がかかります。<br>\
                      読み込まれない場合、取得枚数を減らしてみてください。'
    )

imageclf/views.py
import codecs
import os
import json
import pickle
import numpy as np
import pandas as pd
# from sklearn import 
from requests_oauthlib import OAuth1Session
import requests
from io import BytesIO
import makecsv


from django.shortcuts import render
from django.http import HttpResponse

from getImagesFromTwitter.views import get_items_from_tweet
from imageclf.forms import IllustratorForm

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



APIKEY = os.environ.get('ApiKey_TW')
APISECRETKEY = os.environ.get('ApiSecretKey_TW')


def index(request):
    return render(
            request,
            'imageclf/index.html',
            {}
    )

def get_and_classify_images(request):
    """twitter user名(@以下)から,画像ツイートを取得する。

    取得した画像を分類して表示する。
    """
    if request.method == 'POST':
        form = IllustratorForm(request.POST)
        if form.is_valid():
            max_num_img = form.cleaned_data.get('img_number')
            # tweets_with_photo = []  # tweet単位
            tweets_for_render = []  # 画像単位
            twitter_session = OAuth1Session(APIKEY, APISECRETKEY)
            # 初回はmax_idを指定したくない。Noneにすれば指定なしと同じになる。
            max_id = None
            n = 3200 / 200   # ツイート取得可能数
            for i in range(int(n)):
                params = {
                        'screen_name': form.cleaned_data.get('name'),
                        'count': 200,           # 1回のgetにおける最大値
                        'exclude_replies': True,
                        'include_rts': False,
                        'max_id': max_id
                }
                response = twitter_session.get(
                        url='https://api.twitter.com/1.1/statuses/user_timeline.json',
                        params=params
                )
                if response.status_code != 200:
                    return HttpResponse('取得失敗しました')
                tweets = json.loads(response.text)
                # 3,200ツイート以下だった場合,取得できなかった時点で抜ける。
                if tweets == []:
                    break
                for tweetobj in tweets:
                    # id=0のmediatypeをチェックする.
                    try:
                        mediatype = tweetobj['extended_entities']['media'][0]['type'] 
                    except Exception:
                        mediatype = None
                    if mediatype and (mediatype == 'photo'):
                        # mediasはgenerator.
                        medias = get_items_from_tweet(tweetobj)
                        # 画像ごとのobjectにしてlistに入れる。
                        tweets_for_render.extend(list(medias))
                if len(tweets_for_render) >= max_num_img:
                    break
                max_id = tweetobj.get('id') - 1
            if tweets_for_render == []:
                return HttpResponse('画像はありません')

            if form.cleaned_data.get('clf_status') == 'clf':
                # すでにmediaが存在しないかチェック。
                # process with classifier
                path = os.path.join(BASE_DIR, 'final_tool2.dump')
                with open(path, mode='rb') as f:
                    data = pickle.load(f)
                scaler = data['scaler']
                X_train = data['X_train']
                clf = data['clf']
                scaler.fit(X_train)

                illusts = []
                photos = []

                for media in tweets_for_render:
                    response = requests.get(media['media_url_https'])
                    if response.status_code == 200:
                        fileobj = BytesIO(response.content)
                        temp = makecsv.get_array_from_imgfile(fileobj, color='RGB')
                        mean = np.mean(temp, axis=0)
                        mean = mean.reshape((1,-1))
                        variance = np.var(temp, axis=0)
                        variance = variance.reshape((1,-1))
                        qs = qsorigin = np.percentile(
                                temp,
                                [75, 50, 25],
                                axis=0
                        )
                        qs = qs.reshape((1, -1))
                        features = np.concatenate((mean, variance, qs), axis=1)
                        features_scaled = scaler.transform(features)
                        predict = clf.predict(features_scaled)[0]
                        if predict == 0:
                            proba = clf.predict_proba(features_scaled)[0,0]
                            media['proba'] = round(proba, ndigits=2)
                            illusts.append(media)
                        elif predict == 1:
                            proba = clf.predict_proba(features_scaled)[0,1]
                            media['proba'] = round(proba, ndigits=2)
                            photos.append(media)
            else:  # 分類しない時
                return render(
                    request,
                    'imageclf/show_images.html', 
                    {
                        'images': tweets_for_render,
                    }
                )

            # redirectした方がいい
            illusts = sorted(illusts, key=lambda x: x['proba'], reverse=True)
            photos = sorted(photos, key= lambda x: x['proba'], reverse=True)
            return render(
                request,
                'imageclf/show_images.html', 
                {
                    'illust_data': illusts,
                    'photo_data': photos,
                }
            )
    else:
        form = IllustratorForm()
    # GET時とform.is_varid() == False時はform入力画面へ。
    return render(
            request,
            'imageclf/get_illustrator_name.html',
            {
                'forms': form,
            }
    )

imageclf/templates/imageclf/get_illustrator_name.html
{% extends "imageclf/index.html" %}
{% load static %}

{% block title_block %}username form{% endblock %}

{% block main_block %}
<div class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2>
          画像を取得したい<strong>twitterユーザのID</strong>を入力してください
        </h2>
        <p class="text-danger">@(アットマーク)は入力しないでください!</p>
      </div>
      <div class="col-12">
        <form action="{% url 'imageclf:clf' %}" method='POST' class="m-3">
          {% csrf_token %}
          {% for form in forms %}
            {{ form.label }}
            {{ form }}
            <div class="text-muted">
              {{ form.help_text|safe }}
            </div>
          {% endfor %}
          <button type="submit" class="btn btn-primary mt-2">GO!</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

imageclf/templates/imageclf/index.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143259112-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-143259112-1');
    </script>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-=no">
    <link
    href="https://fonts.googleapis.com/css?family=Kosugi|Notable|Mitr"
    rel="stylesheet">
    <title>
      {% block title_block %}index{% endblock %}
    </title>
    <link rel="stylesheet"
          href={% static "node_modules/bootstrap/dist/css/bootstrap.min.css" %}>
    <style>
      .footer {
        background-color: #f0f0f0;
      }
      main {
        font-family: 'Kosugi', serif;
      }
      button {
        font-family: 'Mitr';
      }

    {% block style_add_block %}{% endblock %}
    </style>
  </head>

  <body>
    <main>
    {% block main_block %}
      <div>
        <a class="btn btn-outline-primary m-4"
           href="{% url 'imageclf:clf' %}">
          イラストGET
        </a>  
      </div>
    {% endblock %}
    </main>

    <footer class="footer mt-auto py-3">
      <div class="container">
        <a href="mailto:qtatsunishiura@gmail.com"
           target="_blank">連絡(メール)はこちら</a>
        <p class="text-muted">© 2018 Kyutatsu</p>
      </div>
    </footer>
    <script src={% static "node_modules/jquery/dist/jquery.slim.min.js" %}></script>
    <script src={% static "node_modules/popper.js/dist/umd/popper.min.js" %}></script>
    <script src={% static "node_modules/bootstrap/dist/js/bootstrap.min.js" %}></script>
  </body>
</html>

imageclf/templates/imageclf/show_images.html
{% extends "imageclf/index.html" %}
{% load static %}

{% block title_block %}results{% endblock %}

{% block style_add_block %}
      .sizeofthumb {
        width: 33%;
        height: auto;
      }
{% endblock %}

{% block main_block %}

<a class="btn btn-primary m-1 p-1"
   href="{% url 'imageclf:index' %}">
  戻る
</a>

{% if not images %}
<div class="container">
  <div class="row">
    <div class="col-md-6 bg-secondary">
        <h2 class="col text-white align-self-center shadow">イラスト</h2>
        <div class="d-flex flex-wrap">
            {% for img in illust_data %}
            <div class="sizeofthumb p-2 shadow">
                      <a href="{{ img.tweet_url }}" target="_blank">
                        <img class="img-fluid" src="{{ img.media_url_https }}">
                      </a>
                      <p>{{ img.proba }}</p>
                      {% if img.proba < 0.75 %}
                        <p class="text-danger">イラストじゃないかも？？</p>
                      {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="col-md-6 bg-light">
      <h2 class="col align-self-center shadow">写真</h2>
      <div class="d-flex flex-wrap">
          {% for img in photo_data %}
          <div class="sizeofthumb p-2 shadow">
                    <a href="{{ img.tweet_url }}" target="_blank">
                      <img class="img-fluid" src="{{ img.media_url_https }}">
                    </a>
                    <p>{{ img.proba }}</p>
                    {% if img.proba < 0.75 %}
                      <p class="text-danger">写真じゃないかも？？</p>
                    {% endif %}
          </div>
          {% endfor %}
      </div>
    </div>
  </div>
</div>
{% else %}
      <div class="d-flex flex-wrap">
          {% for img in images %}
          <div class="sizeofthumb p-2">
                    <a href="{{ img.tweet_url }}" target="_blank">
                      <img class="img-fluid" src="{{ img.media_url_https }}">
                    </a>
                    <!--
                    <p>{{ img.text }}</p>
                    -->
          </div>
          {% endfor %}
      </div>
{% endif %}
{% endblock %}